var post = {
	"type": "FeatureCollection",
	"features": [
{ "type": "Feature", 
  "properties": { "amenity": "post_office", "name": "Bududa Post Office",  "addr_stree": null, "addr_city": null, "addr_house": null, "opening_ho": null, "name_en": null, "phone": null, "payment_cr": null, "short_name": null, "drive_thro": null, "note": null, "email": null, "addr_hou_1": null, "shop": null, "network": null, "addr_pobox": null, "brand": null, "fee": null, "addr_postc": null, "payment__1": null, "VISA": null, "name_de": null, "addr_block": null, "addr_subur": null, "descriptio": null, "female": null, "male": null, "type": null, "bed_count": null, "addr_distr": null, "isced_leve": null, "wikidata": null, "handler_nu": null, "addr_subco": null, "addr_paris": null, "street": null }, "geometry": { "type": "Point", "coordinates": [ 34.3313114, 1.0105634 ] } },
{ "type": "Feature", "properties": { "amenity": "post_office", "name": "Post Office Mbale", "addr_stree": null, "addr_city": null, "addr_house": null, "opening_ho": null, "name_en": null, "phone": null, "payment_cr": null, "short_name": null, "drive_thro": null, "note": null, "email": null, "addr_hou_1": null, "shop": null, "network": null, "addr_pobox": null, "brand": null, "fee": null, "addr_postc": null, "payment__1": null, "VISA": null, "name_de": null, "addr_block": null, "addr_subur": null, "descriptio": null, "female": null, "male": null, "type": null, "bed_count": null, "addr_distr": null, "isced_leve": null, "wikidata": null, "handler_nu": null, "addr_subco": null, "addr_paris": null, "street": null }, "geometry": { "type": "Point", "coordinates": [ 34.1827896, 1.0711121 ] } },
{ "type": "Feature", "properties": { "amenity": "post_office", "name": "Posta Uganda Nakawa", "addr_stree": null, "addr_city": null, "addr_house": null, "opening_ho": null, "name_en": "Nakawa Post Office", "phone": null, "payment_cr": null, "short_name": null, "drive_thro": null, "note": null, "email": null, "addr_hou_1": null, "shop": null, "network": null, "addr_pobox": null, "brand": null, "fee": null, "addr_postc": null, "payment__1": null, "VISA": null, "name_de": null, "addr_block": null, "addr_subur": null, "descriptio": null, "female": null, "male": null, "type": null, "bed_count": null, "addr_distr": null, "isced_leve": null, "wikidata": null, "handler_nu": null, "addr_subco": null, "addr_paris": null, "street": null }, "geometry": { "type": "Point", "coordinates": [ 32.6142633, 0.327392099999983 ] } },
{ "type": "Feature", "properties": { "amenity": "post_office", "name": "Mengo Post Office", "addr_stree": "Kabaka Njagala Road", "addr_city": "Kampala", "addr_house": null, "opening_ho": "Mo-Sa 09:00-18:00", "name_en": null, "phone": null, "payment_cr": null, "short_name": null, "drive_thro": null, "note": null, "email": null, "addr_hou_1": null, "shop": null, "network": null, "addr_pobox": null, "brand": null, "fee": null, "addr_postc": null, "payment__1": null, "VISA": null, "name_de": null, "addr_block": null, "addr_subur": null, "descriptio": null, "female": null, "male": null, "type": null, "bed_count": null, "addr_distr": null, "isced_leve": null, "wikidata": null, "handler_nu": null, "addr_subco": null, "addr_paris": null, "street": null }, "geometry": { "type": "Point", "coordinates": [ 32.558863100000018, 0.308897899999989 ] } }
]
}
